//! Generic worker tests
//!
//! These tests are generated by the `generate_worker_tests!` macro and cover
//! basic Worker functionality that should work with any runtime implementation.

#[cfg(feature = "v8")]
use openworkers_runtime_v8::Worker;

#[cfg(feature = "v8")]
openworkers_runner::generate_worker_tests!(Worker);
